ALTER TABLE boards ADD COLUMN db_type TEXT NOT NULL DEFAULT 'local';
ALTER TABLE boards ADD COLUMN connection_string TEXT DEFAULT '';
ALTER TABLE people ADD COLUMN board_id INTEGER REFERENCES boards(id) ON DELETE CASCADE;
